version: "3.8"

services:
  app:
    image: albert/tchapbot
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 .
    environment:
      - VERBOSE=true
      - SYSTEMD_LOGGING=True
      - SESSION_PATH=/data/session.txt
      - JOIN_ON_INVITE=${JOIN_ON_INVITE}
      - SALT=${SALT}
      - MATRIX_HOME_SERVER=${MATRIX_HOME_SERVER}
      - MATRIX_BOT_USERNAME=${MATRIX_BOT_USERNAME}
      - MATRIX_BOT_PASSWORD=${MATRIX_BOT_PASSWORD}
      - ERRORS_ROOM_ID=${ERRORS_ROOM_ID}
      - USER_ALLOWED_DOMAINS=${USER_ALLOWED_DOMAINS}
      - GROUPS_USED=["basic", "albert"]
      - ALBERT_API_URL=${ALBERT_API_URL}
      - ALBERT_API_TOKEN=${ALBERT_API_TOKEN}
      - ALBERT_MODEL_NAME=${ALBERT_MODEL_NAME}
      - ALBERT_MODE=${ALBERT_MODE}
    ports:
      - 443:443
      - 80:80
    volumes:
      - /data/tchapbot:/data
    restart: always
